kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storability
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: staas-bs03a-okd-nas
